---
# tasks file for ansible-role-redis
- name: Install dirmngr
  ansible.builtin.apt:
    name: dirmngr
    state: present
    update_cache: yes

- name: Add Redis PPA repository
  ansible.builtin.apt_repository:
    repo: ppa:redislabs/redis
    state: present

- name: Install Redis
  ansible.builtin.apt:
    name: redis
    state: present
